// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esmskhfhqbjmxyoiggzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzbXNraGZocWJqbXh5b2lnZ3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NDU2MjQsImV4cCI6MjA1OTQyMTYyNH0.J-aW_Uzx_rcw1z0Fbf1wqhJtNvF9-1GnLqjNhCbEhck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);